#!/bin/sh
# Copyright (C) 2001,2002 Federico Montesino Pouzols
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This is system dependent.
libtoolize --copy --force
aclocal -I m4
autoheader
automake --add-missing --copy
autoconf
rm -rf config.cache
